<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Accès données">
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup Label="Identité et autorité OIDC">
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageVersion Include="Open.IdentityServer" Version="2.0.0" />
    <PackageVersion Include="Open.IdentityServer.AspNetIdentity" Version="2.0.0" />
    <PackageVersion Include="Open.IdentityServer.EntityFramework" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Label="Web">
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup Label="Images">
    <PackageVersion Include="SkiaSharp" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="4.151.1" />
  </ItemGroup>

  <ItemGroup Label="Stockage objet">
    <PackageVersion Include="AWSSDK.S3" Version="4.0.15.2" />
  </ItemGroup>

  <ItemGroup Label="Tests">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

</Project>
