<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Dialecte SQLite pour Cratebase.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cratebase.Data\Cratebase.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

</Project>
